//{{NO_DEPENDENCIES}}
// Microsoft Visual C++에서 생성한 포함 파일입니다.
// Anemone.rc에서 사용되고 있습니다.
//
#define IDC_MYICON                      2
#define IDOK2                           3
#define IDM_SETTING_OPENDIC             3
#define IDC_TRANSWIN_COPY               3
#define IDOK3                           4
#define IDM_SETTING_OPENINI             4
#define IDC_TRANSWIN_FILETRANS          4
#define IDOK4                           5
#define IDM_SETTING_WINRESET            5
#define IDC_TRANSWIN_CLEAR              5
#define IDOK5                           6
#define IDM_SETTING_ADV                 6
#define IDC_TRANSWIN_CLOSE              6
#define IDOK6                           7
#define IDM_SETTING_CLOSE               7
#define IDD_ANEMONE_DIALOG              102
#define IDS_APP_TITLE                   103
#define IDD_ABOUTBOX                    103
#define IDM_ABOUT                       104
#define IDM_EXIT                        105
#define IDI_ANEMONE                     107
#define IDI_SMALL                       108
#define IDC_ANEMONE                     109
#define IDR_MAINFRAME                   128
#define IDD_SETTING                     129
#define IDD_TRANSWIN                    130
#define IDC_ANEMONEWND                  131
#define IDM_TERMINATE_ANEMONE           1001
#define IDM_TEMP_CLICK_THOUGH           1002
#define IDM_WND_BORDER_MODE             1003
#define IDC_CHECK1                      1004
#define IDC_SETTING_TOPMOST             1004
#define IDC_TRANSWIN_TRANS_ONEGO        1004
#define IDC_RADIO1                      1005
#define IDC_SETTING_TEXTALIGN_LEFT      1005
#define IDC_CHECK2                      1006
#define IDC_SETTING_MAGNETIC_TOPMOST    1006
#define IDC_SETTING_MAGNETIC_MINIMIZE   1006
#define IDC_CHECK3                      1007
#define IDC_SETTING_HIDEWIN             1007
#define IDC_CHECK4                      1008
#define IDC_SETTING_HIDEWIN_UNWATCH_CLIPBOARD 1008
#define IDC_CHECK5                      1009
#define IDC_SETTING_HIDEWIN_UNLOCK_HOTKEY 1009
#define IDC_CHECK6                      1010
#define IDC_SETTING_CLIPBOARD_WATCH     1010
#define IDC_CHECK7                      1011
#define IDC_SETTING_WNDCLICK_THOUGH     1011
#define IDC_CHECK8                      1012
#define IDC_SETTING_USE_MAGNETIC        1012
#define IDC_CHECK9                      1013
#define IDC_SETTING_WND_BORDER_MODE     1013
#define IDC_CHECK10                     1014
#define IDC_SETTING_PRINT_ORGTEXT       1014
#define IDC_CHECK11                     1015
#define IDC_SETTING_PRINT_ORGNAME       1015
#define IDC_CHECK12                     1016
#define IDC_SETTING_SEPERATE_NAME       1016
#define IDC_CHECK13                     1017
#define IDC_SETTING_REPEAT_TEXT         1017
#define IDC_CHECK14                     1018
#define IDC_SETTING_TEXTEND_NAME        1018
#define IDC_CHECK15                     1019
#define IDC_SETTING_FORCE_ANEDIC        1019
#define IDC_CHECK16                     1020
#define IDC_SETTING_ANE_REMOCON         1020
#define IDC_CHECK17                     1021
#define IDC_SETTING_EXTERN_HOTKEY       1021
#define IDC_                            1021
#define IDC_000                         1021
#define IDC_RADIO2                      1022
#define IDC_SETTING_TEXTALIGN_MID       1022
#define IDC_RADIO3                      1023
#define IDC_SETTING_TEXTALIGN_RIGHT     1023
#define IDC_SLIDER1                     1024
#define IDC_SETTING_BACKGROUND_TRACKBAR 1024
#define IDC_BUTTON1                     1025
#define IDC_SETTING_BACKGROUND_COLOR    1025
#define IDC_CHECK18                     1026
#define IDC_SETTING_BACKGROUND_SWITCH   1026
#define IDC_BUTTON2                     1027
#define IDC_SETTING_TEXTSIZE_MINUS      1027
#define IDC_CHECK19                     1028
#define IDC_SETTING_NAME_SHADOW         1028
#define IDC_BUTTON3                     1029
#define IDC_SETTING_TEXTSIZE_PLUS       1029
#define IDC_SLIDER2                     1030
#define IDC_TEXTSIZE_TRACKBAR           1030
#define IDC_SETTING_TEXTSIZE_TRACKBAR   1030
#define IDC_BUTTON4                     1031
#define IDC_SETTING_NAME_COLOR          1031
#define IDC_BUTTON5                     1032
#define IDC_SETTING_NAME_OUTLINE1       1032
#define IDC_BUTTON6                     1033
#define IDC_SETTING_NAME_OUTLINE2       1033
#define IDC_BUTTON7                     1034
#define IDC_SETTING_NAME_FONT           1034
#define IDC_BUTTON8                     1035
#define IDC_SETTING_ORG_COLOR           1035
#define IDC_BUTTON9                     1036
#define IDC_SETTING_ORG_OUTLINE1        1036
#define IDC_BUTTON10                    1037
#define IDC_SETTING_ORG_OUTLINE2        1037
#define IDC_BUTTON11                    1038
#define IDC_SETTING_ORG_FONT            1038
#define IDC_CHECK20                     1039
#define IDC_SETTING_ORG_SHADOW          1039
#define IDC_BUTTON12                    1040
#define IDC_SETTING_TRANS_COLOR         1040
#define IDC_BUTTON13                    1041
#define IDC_SETTING_TRANS_OUTLINE1      1041
#define IDC_BUTTON14                    1042
#define IDC_SETTING_TRANS_OUTLINE2      1042
#define IDC_BUTTON15                    1043
#define IDC_SETTING_TRANS_FONT          1043
#define IDC_CHECK21                     1044
#define IDC_SETTING_TRANS_SHADOW        1044
#define IDC_SLIDER3                     1045
#define IDC_SETTING_SHADOW_TRACKBAR     1045
#define IDC_SETTING_CLIP_TRACKBAR       1045
#define IDC_BUTTON16                    1046
#define IDC_SETTING_UPDATE_NOTIFY       1046
#define IDC_CHECK22                     1047
#define IDM_SETTING_EXIT                1047
#define IDC_SETTING_BACKGROUND_TEXT     1048
#define IDC_SLIDER4                     1049
#define IDC_SETTING_TEXTMARGIN_Y_TRACKBAR 1049
#define IDC_SLIDER5                     1050
#define IDC_SETTING_TEXTMARGIN_X_TRACKBAR 1050
#define IDC_TEXTSIZE_TEXT               1051
#define IDC_SETTING_TEXTSIZE_TEXT       1051
#define IDC_SETTING_OUTLINE1_SIZE_MINUS 1052
#define IDC_SETTING_OUTLINE1_SIZE_PLUS  1053
#define IDC_SETTING_OUTLINE1_SIZE_TRACKBAR 1054
#define IDC_SETTING_OUTLINE1_SIZE_TEXT  1055
#define IDC_SETTING_OUTLINE2_SIZE_MINUS 1056
#define IDC_SETTING_OUTLINE2_SIZE_PLUS  1057
#define IDC_SETTING_OUTLINE2_SIZE_TRACKBAR 1058
#define IDC_SETTING_OUTLINE2_SIZE_TEXT  1059
#define IDC_SETTING_SHADOW_TEXT         1060
#define IDC_SETTING_SHADOW_ALPHA_TEXT   1060
#define IDC_SETTING_EXTERN_HOTKEY2      1060
#define IDC_SETTING_TEXTMARGIN_Y_TEXT   1061
#define IDC_SETTING_TEXTMARGIN_X_TEXT   1062
#define IDC_SETTING_TEXTMARGIN_NAME_TRACKBAR 1063
#define IDC_EDIT1                       1063
#define IDC_TRANSWIN_SRC                1063
#define IDC_SETTING_TEXTMARGIN_NAME_TEXT 1064
#define IDC_EDIT2                       1064
#define IDC_TRANSWIN_TRANSLATE          1064
#define IDC_TRANSWIN_DEST               1065
#define IDC_SETTING_NAME_SHADOW_COLOR   1065
#define IDC_COLORDLG_ALPHA_TRACKBAR     1066
#define IDC_SETTING_CLIP_TEXT           1066
#define IDC_COLORDLG_ALPHA_EDIT         1067
#define IDC_SETTING_REPEAT_TEXT2        1067
#define IDC_BUTTON17                    1068
#define IDC_SETTING_UPDATE_CHECK        1068
#define IDC_SETTING_TRANS_SHADOW_COLOR  1069
#define IDC_SETTING_ORG_SHADOW_COLOR    1070
#define IDC_SETTING_SHADOW_SIZE_TRACKBAR 1071
#define IDC_SETTING_SHADOW_X_TRACKBAR   1071
#define IDC_SETTING_SHADOW_SIZE_TEXT    1072
#define IDC_SETTING_SHADOW_X_TEXT       1072
#define IDC_SETTING_SHADOW_Y_TRACKBAR   1073
#define IDC_SETTING_SHADOW_Y_TEXT       1074
#define IDM_WINDOW_SETTING              1201
#define IDM_SETTING_CHECK               1202
#define IDM_TEXT_PREV                   1203
#define IDM_TEXT_NEXT                   1204
#define IDM_OPENDIC                     1205
#define IDM_OPENINI                     1206
#define IDM_TOPMOST                     1207
#define IDM_TEXTALIGN_LEFT              1208
#define IDM_TEXTALIGN_MID               1209
#define IDM_TEXTALIGN_RIGHT             1210
#define IDM_SEPERATE_NAME               1211
#define IDM_EXTERN_HOTKEY               1212
#define IDM_PRINT_ORGTEXT               1213
#define IDM_PRINT_ORGNAME               1214
#define IDM_TRANS_PROGRESS              1215
#define IDM_TRANS_COMPLETE              1216
#define IDM_TRANS_ABORT                 1217
#define IDM_TRANS_ERROR                 1218
#define IDM_TRANS_START                 1219
#define ID_Menu                         32771
#define ID_32772                        32772
#define ID_32773                        32773
#define ID_ANEMONE_32774                32774
#define ID_ANEMONE_32775                32775
#define ID_Menu32776                    32776
#define IDM_CLIPBOARD_SWITCH            32777
#define IDM_WINDOW_THROUGH_CLICK        32778
#define IDM_SIZEABLE_MODE               32779
#define IDM_WINDOW_SIZEABLE_MODE        32780
#define IDM_TEMP_WINDOW_HIDE            32781
#define IDM_WINDOW_VISIBLE              32782
#define IDM_WINDOW_TRANS                32784
#define IDM_WINDOW_FILETRANS            32785
#define IDM_HIDEWIN_UNLOCK_HOTKEY       32786
#define ID_ANEMONE_32786                32786
#define IDM_HIDEWIN_UNWATCH_CLIPBOARD   32787
#define ID_32787                        32787
#define IDM_MAGNETIC_MODE               32788
#define ID_32788                        32788
#define IDM_RESTORE_PARENT              32789
#define ID_Menu32789                    32789
#define IDM_TRANSTEXT_WNDMENU           32790
#define ID_Menu32790                    32790
#define IDM_TRANSTEXT_WNDTEXT           32791
#define IDM_DESTROY_MENU                32792
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        131
#define _APS_NEXT_COMMAND_VALUE         32791
#define _APS_NEXT_CONTROL_VALUE         1069
#define _APS_NEXT_SYMED_VALUE           110
#endif
#endif
